FROM ubuntu:12.04
MAINTAINER Jean-François Roche <jfroche@affinitic.be>
ENV HOME /root
WORKDIR /root/
ENV VERSION $VERSION
ENV BUILD $BUILD
RUN apt-get update
RUN apt-get install -y build-essential libsqlite3-dev zlib1g-dev libncurses5-dev libgdbm-dev libbz2-dev libreadline6-dev libssl-dev libdb-dev checkinstall wget ca-certificates unzip
ADD build27.sh /root/build27.sh
RUN /root/build27.sh
RUN dpkg -i /root/Python-$VERSION/python27_2.7*_amd64.deb
RUN /opt/python$VERSION/bin/python2.7 -c 'import ssl'
RUN /opt/python$VERSION/bin/python2.7 -c 'import zlib'
RUN /opt/python$VERSION/bin/python2.7 -c 'import crypt'
RUN /opt/python$VERSION/bin/python2.7 -c 'import gzip'
RUN wget https://pypi.python.org/packages/source/s/setuptools/setuptools-3.5.1.zip
RUN unzip setuptools-3.5.1.zip
RUN cd setuptools-3.5.1 && checkinstall --install=no --requires "python27 \(= $VERSION-$BUILD\)" --exclude /opt/python$VERSION/lib/python2.7/site-packages/easy-install.pth --pkgname=python27-setuptools --pkgversion=3.5.1 --pkgrelease=$BUILD --nodoc --maintainer=jfroche@affinitic.be --default /opt/python$VERSION/bin/python setup.py install
RUN checkinstall --install=no --pkgname=python27-virtualenv --requires "python27 \(= $VERSION-$BUILD\), python27-setuptools" --pkgversion=1.11.6 --pkgrelease=$BUILD --nodoc --maintainer=jfroche@affinitic.be --default /opt/python$VERSION/bin/easy_install virtualenv
